# Generated by Django 2.1.7 on 2019-03-11 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='locationpoint',
            name='day_entry',
        ),
        migrations.AddField(
            model_name='journey',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='core.Journey'),
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='journey',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='LocationPoint',
        ),
        migrations.AddField(
            model_name='entryimage',
            name='day_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.DayEntry'),
        ),
    ]
